---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic
  namespace: operator
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/metrics"
    - "nodes/stats"
    - "nodes/proxy"
    - "pods"
    - "secrets"
    - "services"
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic
  namespace: operator
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: newrelic-infra
  namespace: operator
  labels:
    app: newrelic-infra
spec:
  selector:
    matchLabels:
      name: newrelic-infra
  updateStrategy:
      type: RollingUpdate # Only supported in Kubernetes version 1.6 or later.
  template:
    metadata:
      labels:
        name: newrelic-infra
      annotations:
        # Needed for Kubernetes versions prior to 1.6.0, where tolerations were set via annotations.
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"operator": "Exists", "effect": "NoSchedule"},{"operator": "Exists", "effect": "NoExecute"}]
    spec:
      serviceAccountName: newrelic
      hostNetwork: true # This option is a requirement for the Infrastructure Agent to report the proper hostname in New Relic.
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: newrelic-infra
          image: newrelic/infrastructure-k8s:1.17.0
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 300M
            requests:
              cpu: 100m
              memory: 150M
          volumeMounts:
            - mountPath: /host
              name: host-volume
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: host-docker-socket
            - mountPath: /var/db/newrelic-infra/integrations.d/
              name: nri-default-integration-cfg-volume
            - mountPath: /etc/newrelic-infra/integrations.d/
              name: nri-integration-cfg-volume
          env:
            - name: "CLUSTER_NAME"
              value: "YOUR_CLUSTER_NAME"
            - name: "NRIA_LICENSE_KEY"
              value: "YOUR_LICENSE_KEY"
            - name: "NRIA_VERBOSE"
              value: "0"
           # - name: "KUBE_STATE_METRICS_POD_LABEL" # Enables discovery of the KSM pod via a label. The value of the label needs to be "true".
           #   value: "<YOUR_LABEL>" # Remember to replace this placeholder with the label name of your choice.
           # - name: "KUBE_STATE_METRICS_PORT" # If the KUBE_STATE_METRICS_POD_LABEL is present, it changes the port queried in the pod.
           #   value: "8080"
           # - name: "KUBE_STATE_METRICS_SCHEME" # If the KUBE_STATE_METRICS_POD_LABEL is present, it changes the scheme used to send to request to the pod.
           #   value: "http"
           # - name: "CADVISOR_PORT" # Enable direct connection to cAdvisor by specifying the port. Needed for Kubernetes versions prior to 1.7.6.
           #   value: "4194"
           # - name: "KUBE_STATE_METRICS_URL" # If this value is specified then discovery process for kube-state-metrics endpoint won't be triggered.
           #   value: "http://172.17.0.3:8080" # This is example value. Only HTTP request is accepted.
           # - name: "ETCD_TLS_SECRET_NAME" # Name of the secret containing the cacert, cert and key used for setting the mTLS config for retrieving metrics from ETCD.
           #   value: "newrelic-infra-etcd-tls-secret"
           # - name: "ETCD_TLS_SECRET_NAMESPACE" # Namespace where the the secret specified in ETCD_TLS_SECRET_NAME was created.
           #   value: "default"
           # Note: Usage of API_SERVER_SECURE_PORT has been deprecated in favor of API_SERVER_ENDPOINT_URL.
           # - name: API_SERVER_SECURE_PORT
           #   value: "6443"
           # - name: "SCHEDULER_ENDPOINT_URL"
           #   value: "https://localhost:10259"
           # - name: "ETCD_ENDPOINT_URL"
           #   value: "https://localhost:9979"
           # - name: "CONTROLLER_MANAGER_ENDPOINT_URL"
           #   value: "https://localhost:10257"
           # - name: "API_SERVER_ENDPOINT_URL"
           #   value: "https://localhost:6443"
            - name: "NRIA_DISPLAY_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"
            - name: "NRK8S_NODE_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"
            - name: "NRIA_CUSTOM_ATTRIBUTES"
              value: '{"clusterName":"$(CLUSTER_NAME)"}'
            - name: "NRIA_PASSTHROUGH_ENVIRONMENT"
              value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME,CADVISOR_PORT,NRK8S_NODE_NAME,KUBE_STATE_METRICS_URL,KUBE_STATE_METRICS_POD_LABEL,ETCD_TLS_SECRET_NAME,ETCD_TLS_SECRET_NAMESPACE,API_SERVER_SECURE_PORT,KUBE_STATE_METRICS_SCHEME,KUBE_STATE_METRICS_PORT,SCHEDULER_ENDPOINT_URL,ETCD_ENDPOINT_URL,CONTROLLER_MANAGER_ENDPOINT_URL,API_SERVER_ENDPOINT_URL,DISABLE_KUBE_STATE_METRICS"
      volumes:
        - name: host-volume
          hostPath:
            path: /
        - name: host-docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: nri-default-integration-cfg-volume
          configMap:
            name: nri-default-integration-cfg
        - name: nri-integration-cfg-volume
          configMap:
            name: nri-integration-cfg
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
        - operator: "Exists"
          effect: "NoExecute"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-default-integration-cfg # integrations config provided by default
  namespace: operator
data:
  nri-kubernetes-config.yml: |
    integration_name: com.newrelic.kubernetes
    instances:
      - name: nri-kubernetes
        command: metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg # aimed to be safely overridden by users
  namespace: operator
data:
  jmx-config.yml: |
    ---
    # Run auto discovery to find pods with label "clusterId=operator"
      # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
      discovery:
        command:
          # Run NRI Discovery for Kubernetes
          # https://github.com/newrelic/nri-discovery-kubernetes
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes
          match:
            label.clusterId: operator
      integrations:
        - name: nri-jmx
          env:
            # Using the discovered IP as the host address
            JMX_HOST: ${discovery.ip}
            JMX_PORT: 7203
            COLLECTION_FILES: ${config.path}
          config:
            collect:
              - domain: kafka.server
                event_type: KafkaServer
                beans:
                  - query: "type=BrokerTopicMetrics,name=BytesInPerSec"
                    attributes:
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
                  - query: "type=BrokerTopicMetrics,name=BytesOutPerSec"
                    attributes:
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
                  - query: "type=BrokerTopicMetrics,name=MessagesInPerSec"
                    attributes:
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
                  - query: "type=ReplicaManager,*"
                    attributes:
                      - "Value"
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
                  - query: "type=ReplicaFetcherManager,name=MaxLag,clientId=Replica"
                    attributes:
                      - "Value"
                  - query: "type=ProducerRequestPurgatory,name=PurgatorySize"
                    attributes:
                      - "Value"
                  - query: "type=FetchRequestPurgatory,name=PurgatorySize"
                    attributes:
                      - "Value"
                  - query: "type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent"
                    attributes:
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
              - domain: kafka.network
                event_type: KafkaNetwork
                beans:
                  - query: "type=RequestMetrics,name=RequestsPerSec,*"
                    attributes:
                      - "MeanRate"
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Count"
                  - query: "type=RequestMetrics,name=TotalTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=RequestMetrics,name=LocalTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=RequestMetrics,name=RemoteTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=RequestMetrics,name=ResponseQueueTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=RequestMetrics,name=RequestQueueTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=RequestMetrics,name=ResponseSendTimeMs,*"
                    attributes:
                      - "Mean"
                      - "Max"
                      - "75thPercentile"
                      - "95thPercentile"
                      - "98thPercentile"
                      - "99thPercentile"
                      - "Count"
                  - query: "type=SocketServer,name=NetworkProcessorAvgIdlePercent"
                    attributes:
                      - "Value"
              - domain: kafka.log
                event_type: KafkaLog
                beans:
                  - query: "type=LogFlushStats,name=LogFlushRateAndTimeMs"
                    attributes:
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Mean"
                      - "98thPercentile"
                      - "Max"
              - domain: kafka.controller
                event_type: KafkaController
                beans:
                  - query: "type=LogFlushStats,name=LogFlushRateAndTimeMs"
                    attributes:
                      - "Value"
                  - query: "type=ControllerStats,*"
                    attributes:
                      - "OneMinuteRate"
                      - "FiveMinuteRate"
                      - "FifteenMinuteRate"
                      - "Mean"
                      - "98thPercentile"
                      - "Max"
              - domain: org.apache.ZooKeeperService
                event_type: ZookeeperService
                beans:
                  - query: "*"
              - domain: kafka.connect
                event_type: KafkaConnect
                beans:
                  - query: "type=connector-metrics,*"
                  - query: "type=task-metrics,*"
                  - query: "type=source-task-metrics,*"
                  - query: "type=sink-task-metrics,*"
                  - query: "type=source-task-metrics,*"
                  - query: "type=sink-task-metrics,*"
                  - query: "type=connect-worker-metrics"
                  - query: "type=connect-worker-rebalance-metrics"
              - domain: kafka.stream
                event_type: KafkaStreams
                beans:
                  - query: "type=stream-metrics,*"
                  - query: "type=stream-task-metrics,*"
                  - query: "type=stream-processor-node-metrics,*"
                  - query: "type=stream-*"
                  - query: "type=stream-record-cache-metrics,*"
              - domain: kafka.rest
                event_type: KafkaRest
                beans:
                  - query: "type=jetty-metrics,*"
                  - query: "type=jersey-metrics,*"
              - domain: java.lang
                event_type: JVMMetrics
                beans:
                  - query: type=GarbageCollector,name=*
                    attributes:
                      - CollectionCount
                      - CollectionTime
                  - query: type=Memory
                    attributes:
                      - HeapMemoryUsage.Committed
                      - HeapMemoryUsage.Init
                      - HeapMemoryUsage.Max
                      - HeapMemoryUsage.Used
                      - NonHeapMemoryUsage.Committed
                      - NonHeapMemoryUsage.Init
                      - NonHeapMemoryUsage.Max
                      - NonHeapMemoryUsage.Used
                  - query: type=Threading
                    attributes:
                      - ThreadCount
                      - TotalStartedThreadCount
                  - query: type=ClassLoading
                    attributes:
                      - LoadedClassCount
                  - query: type=Compilation
                    attributes:
                      - TotalCompilationTime
                  - query: type=OperatingSystem
                    attributes:
                      - SystemLoadAverage
                      - AvailableProcessors
                      - TotalPhysicalMemorySize
                      - FreePhysicalMemorySize
                      - TotalSwapSpaceSize
                      - FreeSwapSpaceSize
                      - OpenFileDescriptorCount
                      - MaxFileDescriptorCount
          labels:
            env: staging